import { expect, test } from '@playwright/test'

test('主要業務フローと3画面が動作する', async ({ page }, testInfo) => {
  const errors:string[]=[]
  page.on('pageerror', e=>errors.push(e.message))
  page.on('console', message=>{if(message.type()==='error')errors.push(message.text())})
  await page.goto('/')
  await expect(page.getByText(/現地確認が必要な農地/)).toHaveCount(0)
  await expect(page.locator('.data-badges')).toHaveCount(0)
  await expect(page.locator('.page-intro p')).toHaveCount(0)
  await expect(page.locator('.eyebrow')).toHaveCount(0)
  await expect(page.getByText('本デモで精度値は主張しません',{exact:true})).toHaveCount(0)
  await expect(page.getByText('全261筆中')).toBeVisible()
  await expect(page.getByRole('heading',{name:'2025年の衛星判定'})).toBeVisible()
  await expect(page.locator('.maplibregl-canvas')).toBeVisible()
  await expect(page.locator('.maplibregl-ctrl-attrib')).toContainText('OpenStreetMap')
  await page.screenshot({ path:`tmp/qa-dashboard-${testInfo.project.name}.png`, fullPage:true })
  await page.getByRole('button',{name:/現地確認リスト/}).first().click()
  await expect(page.getByRole('heading',{name:'現地確認リスト'})).toBeVisible()
  await expect(page.locator('.page-title-row p')).toHaveCount(0)
  await expect(page.getByRole('button',{name:'CSVを出力'})).toBeEnabled()
  const priority=page.getByLabel('優先表示')
  await expect(priority).toHaveValue('cultivation_signal')
  await expect(page.locator('tbody tr').first()).toContainText('作付兆候')
  await expect(page.locator('tbody tr').first()).toContainText('一致')
  await priority.selectOption('review_required')
  await expect(page.locator('tbody tr').first()).toContainText('要確認')
  await expect(page.locator('tbody tr').first()).toContainText('一致')
  if(testInfo.project.name==='desktop-chromium'){
    await page.screenshot({ path:'tmp/qa-candidates.png', fullPage:true })
    await page.getByRole('button',{name:'判定方法'}).click()
    await expect(page.getByRole('heading',{name:'この判定について'})).toBeVisible()
    await expect(page.locator('.page-title-row p')).toHaveCount(0)
    await expect(page.locator('.version-badge')).toHaveCount(0)
    await expect(page.getByText(/S1 58シーン／S2 111シーン/)).toBeVisible()
    await expect(page.getByText(/Cloud Probability 40%未満は未適用/)).toBeVisible()
    await page.screenshot({ path:'tmp/qa-method.png', fullPage:true })
  }
  expect(errors).toEqual([])
})
