import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertCircle, BarChart3, ChevronRight, ClipboardCheck, Download, Filter, HelpCircle, Leaf, ListFilter, LoaderCircle, Map as MapIcon, RotateCcw, Search, ShieldCheck, Trash2 } from 'lucide-react'
import { CHANGE, CROP, MATCH, STATUS, SUBTYPE } from './labels'
import { buildCandidateCsv, csvFilename, sortedCandidates, type CandidatePreference } from './csv'
import { MapPanel } from './components/MapPanel'
import { DetailPanel } from './components/DetailPanel'
import type { ChangeType, FieldCollection, FieldFeature, FieldProperties, Manifest, Methodology, Status, Timeseries } from './types'
import './styles.css'

type Page='dashboard'|'candidates'|'estimate'|'method'
const ALL_STATUSES=Object.keys(STATUS) as Status[]
const isActual=(manifest:Manifest)=>manifest.dataMode.startsWith('actual_sentinel_observations')
const PRIORITY_LABELS:Record<string,string>={declaration:'申告差異',status:'判定状態',change:'年次変化',evidence_uncertainty:'観測の不確かさ',area:'面積'}
const SENSITIVITY_LABELS:Record<string,string>={sar_flood_drop_db:'湛水時のSAR低下量',ndvi_growth_rise:'NDVI生育上昇量',ndvi_peak:'NDVIピーク',ndvi_harvest_drop:'収穫後のNDVI低下量'}

function useData(retry:number){
  const [state,setState]=useState<{loading:boolean;error?:string;manifest?:Manifest;fields?:FieldCollection;timeseries?:Timeseries;methodology?:Methodology}>({loading:true})
  useEffect(()=>{let alive=true;setState({loading:true});const base=import.meta.env.BASE_URL+'data/';Promise.all([fetch(base+'manifest.json'),fetch(base+'field-results.geojson'),fetch(base+'field-timeseries.json'),fetch(base+'methodology.json')]).then(async rs=>{if(rs.some(r=>!r.ok))throw new Error(`成果データを取得できません (${rs.map(r=>r.status).join('/')})`);return Promise.all(rs.map(r=>r.json()))}).then(([manifest,fields,timeseries,methodology])=>alive&&setState({loading:false,manifest,fields,timeseries,methodology})).catch(e=>alive&&setState({loading:false,error:e instanceof Error?e.message:String(e)}));return()=>{alive=false}},[retry]);return state
}

export default function App(){
  const [page,setPage]=useState<Page>('dashboard');const [retry,setRetry]=useState(0);const data=useData(retry)
  const [selectedId,setSelectedId]=useState<string>();const [statuses,setStatuses]=useState<Status[]>(ALL_STATUSES);const [confidence,setConfidence]=useState(0);const [minArea,setMinArea]=useState('');const [maxArea,setMaxArea]=useState('');const [change,setChange]=useState<ChangeType|'all'>('all');const [query,setQuery]=useState('')
  const [candidateIds,setCandidateIds]=useState<Set<string>>(new Set());const [restored,setRestored]=useState(false)
  const props=useMemo(()=>data.fields?.features.map(f=>f.properties)??[],[data.fields])
  const storageKey=data.manifest?`soramamori:candidates:${data.manifest.datasetVersion}:${data.manifest.dataMode}`:'soramamori:candidates'
  useEffect(()=>{if(!props.length||restored)return;const stored=localStorage.getItem(storageKey);let ids:string[];try{ids=stored?JSON.parse(stored):props.map(f=>f.field_id)}catch{ids=props.map(f=>f.field_id)}setCandidateIds(new Set(ids.filter(id=>props.some(f=>f.field_id===id))));setRestored(true)},[props,restored,storageKey])
  useEffect(()=>{if(restored)localStorage.setItem(storageKey,JSON.stringify([...candidateIds]))},[candidateIds,restored,storageKey])
  const filtered=useMemo(()=>{if(!data.fields)return undefined;const min=Number(minArea||0),max=maxArea?Number(maxArea):Infinity,q=query.trim().toLowerCase();return {...data.fields,features:data.fields.features.filter(f=>{const p=f.properties;return statuses.includes(p.status)&&(p.confidence??0)>=confidence&&p.area_ha>=min&&p.area_ha<=max&&(change==='all'||p.change_type===change)&&(!q||p.field_id.toLowerCase().includes(q))})} as FieldCollection},[data.fields,statuses,confidence,minArea,maxArea,change,query])
  useEffect(()=>{if(filtered?.features.length&&!filtered.features.some(f=>f.properties.field_id===selectedId))setSelectedId(filtered.features[0].properties.field_id)},[filtered,selectedId])
  const selected=props.find(f=>f.field_id===selectedId);const selectedSeries=selectedId?data.timeseries?.fields[selectedId]:undefined
  const candidates=useMemo(()=>props.filter(f=>candidateIds.has(f.field_id)),[props,candidateIds])
  const toggleCandidate=useCallback((id:string)=>setCandidateIds(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next}),[])
  if(data.loading)return <div className="loading" role="status"><LoaderCircle className="spin"/><strong>圃場データを読み込んでいます</strong><span>275筆の静的成果を準備中です</span></div>
  if(data.error||!data.manifest||!data.fields||!data.timeseries||!data.methodology)return <div className="error-screen"><AlertCircle/><h1>データを読み込めませんでした</h1><p>{data.error}</p><button className="button button-primary" onClick={()=>setRetry(x=>x+1)}>再読み込み</button></div>
  const nav=(target:Page,label:string,Icon:typeof MapIcon)=><button className={page===target?'active':''} onClick={()=>setPage(target)} aria-current={page===target?'page':undefined}><Icon size={18}/><span>{label}</span>{target==='candidates'&&<b>{candidateIds.size}</b>}</button>
  return <div className="app-shell"><header className="site-header"><div className="brand" onClick={()=>setPage('dashboard')} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setPage('dashboard')}}} role="button" tabIndex={0}><span className="brand-mark"><Leaf/></span><div><strong>そらまもり<em>農地</em></strong><small>衛星データによる作付確認支援</small></div></div><nav aria-label="主要メニュー">{nav('dashboard','圃場を探す',MapIcon)}{nav('candidates','現地確認リスト',ClipboardCheck)}{nav('estimate','調査試算',BarChart3)}{nav('method','判定方法',HelpCircle)}</nav></header>
    <main id="main">{page==='dashboard'&&<Dashboard manifest={data.manifest} all={data.fields} filtered={filtered!} methodology={data.methodology} selected={selected} selectedSeries={selectedSeries} selectedId={selectedId} onSelect={setSelectedId} statuses={statuses} setStatuses={setStatuses} confidence={confidence} setConfidence={setConfidence} minArea={minArea} setMinArea={setMinArea} maxArea={maxArea} setMaxArea={setMaxArea} change={change} setChange={setChange} query={query} setQuery={setQuery} reset={()=>{setStatuses(ALL_STATUSES);setConfidence(0);setMinArea('');setMaxArea('');setChange('all');setQuery('')}} inCandidates={selectedId?candidateIds.has(selectedId):false} onToggle={()=>selectedId&&toggleCandidate(selectedId)} openCandidates={()=>setPage('candidates')}/>} 
      {page==='candidates'&&<Candidates fields={candidates} manifest={data.manifest} methodology={data.methodology} onSelect={id=>{setSelectedId(id);setPage('dashboard')}} onRemove={toggleCandidate} onClear={()=>setCandidateIds(new Set())}/>}
      {page==='estimate'&&<Estimate total={props.length} candidateCount={props.filter(f=>f.auto_candidate).length}/>} 
      {page==='method'&&<Method manifest={data.manifest} methodology={data.methodology}/>}</main>
    <footer><div><strong>そらまもり農地</strong></div><p>Contains modified Copernicus Sentinel data 2024–2025<br/>出典：「筆ポリゴンデータ」（農林水産省・2026年）を加工して作成／© OpenStreetMap contributors</p></footer>
  </div>
}

interface DashProps {manifest:Manifest;all:FieldCollection;filtered:FieldCollection;methodology:Methodology;selected?:FieldProperties;selectedSeries?:Record<string,any>;selectedId?:string;onSelect:(id:string)=>void;statuses:Status[];setStatuses:(s:Status[])=>void;confidence:number;setConfidence:(n:number)=>void;minArea:string;setMinArea:(v:string)=>void;maxArea:string;setMaxArea:(v:string)=>void;change:ChangeType|'all';setChange:(v:ChangeType|'all')=>void;query:string;setQuery:(v:string)=>void;reset:()=>void;inCandidates:boolean;onToggle:()=>void;openCandidates:()=>void}
function Dashboard(p:DashProps){
  const fields=p.filtered.features.map(f=>f.properties);const area=fields.reduce((s,f)=>s+f.area_ha,0);const review=fields.filter(f=>f.auto_candidate).length;const counts=Object.fromEntries(ALL_STATUSES.map(s=>[s,fields.filter(f=>f.status===s).length])) as Record<Status,number>
  const toggleStatus=(s:Status)=>p.setStatuses(p.statuses.includes(s)?p.statuses.filter(x=>x!==s):[...p.statuses,s])
  return <><section className="page-intro"><h1>現地確認が必要な農地を、<br/><em>衛星の変化</em>から絞り込む。</h1></section>
    <section className="summary-grid" aria-label="表示中の集計"><div className="summary primary"><span>表示中</span><strong>{fields.length}<small>筆</small></strong><p>全{p.all.features.length}筆中</p></div><div className="summary"><span>合計面積</span><strong>{area.toFixed(1)}<small>ha</small></strong><p>フィルター対象</p></div><div className="summary alert"><span>自動候補</span><strong>{review}<small>筆</small></strong><p>{fields.length?Math.round(review/fields.length*100):0}% を確認候補</p></div><div className="summary status-breakdown">{ALL_STATUSES.map(s=><div key={s}><i style={{background:STATUS[s].color}}/><span>{STATUS[s].short}</span><strong>{counts[s]}</strong></div>)}</div></section>
    <div className="workspace"><aside className="filter-panel"><div className="panel-heading"><div><h2><Filter size={19}/>確認条件</h2></div><button className="icon-button" onClick={p.reset} aria-label="絞り込みを解除"><RotateCcw/></button></div><label className="search"><Search/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="圃場IDを検索"/></label>
      <fieldset><legend>主判定</legend>{ALL_STATUSES.map(s=><label className="check" key={s}><input type="checkbox" checked={p.statuses.includes(s)} onChange={()=>toggleStatus(s)}/><i style={{background:STATUS[s].color}}/><span>{STATUS[s].label}</span><b>{p.all.features.filter(f=>f.properties.status===s).length}</b></label>)}</fieldset>
      <label className="range-label"><span>証拠の強さ</span><strong>{Math.round(p.confidence*100)}% 以上</strong><input type="range" min="0" max="1" step=".1" value={p.confidence} onChange={e=>p.setConfidence(Number(e.target.value))}/></label>
      <fieldset><legend>面積（ha）</legend><div className="range-inputs"><input type="number" min="0" step=".01" placeholder="下限" value={p.minArea} onChange={e=>p.setMinArea(e.target.value)}/><span>〜</span><input type="number" min="0" step=".01" placeholder="上限" value={p.maxArea} onChange={e=>p.setMaxArea(e.target.value)}/></div></fieldset>
      <label className="select-label"><span>年次変化</span><select value={p.change} onChange={e=>p.setChange(e.target.value as ChangeType|'all')}><option value="all">すべて</option>{Object.entries(CHANGE).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
      <button className="button button-secondary full" onClick={p.reset}><RotateCcw size={17}/>絞り込みを解除</button>
      <div className="field-list-heading"><span><ListFilter size={17}/>圃場一覧</span><b>{fields.length}筆</b></div><div className="field-list">{fields.slice().sort((a,b)=>b.priority_score-a.priority_score).map(f=><button key={f.field_id} className={p.selectedId===f.field_id?'selected':''} onClick={()=>p.onSelect(f.field_id)}><i style={{background:STATUS[f.status].color}}/><span><strong>{f.field_id.slice(-8)}</strong><small>{STATUS[f.status].short}・{f.area_ha.toFixed(2)}ha</small></span><b>{f.priority_score.toFixed(0)}</b><ChevronRight/></button>)}</div>
    </aside><MapPanel data={p.filtered} roi={p.manifest.roi} selectedId={p.selectedId} onSelect={p.onSelect}/><DetailPanel field={p.selected} series={p.selectedSeries} methodology={p.methodology} inCandidates={p.inCandidates} onToggle={p.onToggle}/></div>
    <button className="floating-candidates" onClick={p.openCandidates}><ClipboardCheck/><span>現地確認リスト</span></button></>
}

function Candidates({fields,manifest,methodology,onSelect,onRemove,onClear}:{fields:FieldProperties[];manifest:Manifest;methodology:Methodology;onSelect:(id:string)=>void;onRemove:(id:string)=>void;onClear:()=>void}){
  const [preference,setPreference]=useState<CandidatePreference>('cultivation_signal')
  const ordered=useMemo(()=>sortedCandidates(fields,preference),[fields,preference])
  const download=()=>{const csv=buildCandidateCsv(ordered,manifest);const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=csvFilename();a.click();URL.revokeObjectURL(url)}
  return <section className="standard-page"><div className="page-title-row"><div><h1>現地確認リスト</h1></div><div className="page-actions"><label className="priority-select"><span>優先表示</span><select value={preference} onChange={e=>setPreference(e.target.value as CandidatePreference)}><option value="cultivation_signal">作付兆候</option><option value="review_required">要確認</option><option value="insufficient_observation">観測不足</option></select></label><button className="button button-ghost" onClick={onClear} disabled={!ordered.length}><Trash2/>全削除</button><button className="button button-primary" onClick={download} disabled={!ordered.length} title={!ordered.length?'候補が0件のため出力できません':''}><Download/>CSVを出力</button></div></div>
    {!ordered.length?<div className="empty-state"><ClipboardCheck/><h2>候補はありません</h2><p>圃場詳細から「現地確認候補に追加」してください。候補が0件のためCSVは出力できません。</p></div>:<div className="table-wrap"><table><thead><tr><th>順位</th><th>圃場</th><th>主判定</th><th>申告との関係</th><th>面積</th><th>優先度</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{ordered.map((f,i)=><tr key={f.field_id}><td>{i+1}</td><td><button className="table-link" onClick={()=>onSelect(f.field_id)}>{f.field_id.slice(-8)}</button><small>{f.centroid_lat.toFixed(5)}, {f.centroid_lon.toFixed(5)}</small></td><td><span className={`status-pill ${STATUS[f.status].tone}`}>{STATUS[f.status].short}</span><small>{methodology.reasonLabels[f.reason_codes[0]]??f.reason_codes[0]}</small></td><td><strong className={`match-${f.declaration_match}`}>{MATCH[f.declaration_match]}</strong><small>{CROP[f.declared_crop??'']??'—'}</small></td><td>{f.area_ha.toFixed(3)} ha</td><td><span className="priority-score">{f.priority_score.toFixed(0)}</span><details className="score-details"><summary>内訳</summary>{Object.entries(f.priority_components).map(([k,v])=><span key={k}>{PRIORITY_LABELS[k]??'その他'}: {v.toFixed(1)}</span>)}</details></td><td><button className="icon-button danger" onClick={()=>onRemove(f.field_id)} aria-label={`${f.field_id}を削除`}><Trash2/></button></td></tr>)}</tbody></table></div>}
  </section>
}

function Estimate({total,candidateCount}:{total:number;candidateCount:number}){
  const [rate,setRate]=useState(total?Math.round(candidateCount/total*100):0),[people,setPeople]=useState(2),[minutes,setMinutes]=useState(15),[wage,setWage]=useState(3000),[ops,setOps]=useState(50000),[hoursDay,setHoursDay]=useState(7.5)
  const narrowed=Math.round(total*rate/100),asIs=total*minutes/60*people,toBeH=narrowed*minutes/60*people,saved=asIs-toBeH,asCost=asIs*wage,toCost=ops+toBeH*wage,diff=asCost-toCost
  const input=(label:string,value:number,set:(n:number)=>void,suffix:string)=><label><span>{label}</span><div><input type="number" min="0" value={value} onChange={e=>set(Math.max(0,Number(e.target.value)))}/><b>{suffix}</b></div></label>
  return <section className="standard-page estimate-page"><div className="page-title-row"><div><h1>調査削減シナリオ</h1></div></div><div className="estimate-layout"><div className="form-card"><h2>試算条件</h2><div className="form-grid"><label><span>全対象筆数</span><div><input value={total} disabled/><b>筆</b></div></label>{input('要確認率',rate,setRate,'%')}{input('調査人数',people,setPeople,'人')}{input('1筆あたり',minutes,setMinutes,'分')}{input('人件費',wage,setWage,'円/人時')}{input('衛星解析・運用費',ops,setOps,'円/年')}{input('1人日の稼働',hoursDay,setHoursDay,'時間')}</div></div><div className="results-card"><h2>{narrowed}筆に絞り込み</h2><div className="big-saving"><strong>{saved.toFixed(1)}<small>時間</small></strong><span>推定削減<br/>（{asIs?Math.round(saved/asIs*100):0}%）</span></div><div className="result-bars"><div><span>全筆を確認</span><i><b style={{width:'100%'}}/></i><strong>{asIs.toFixed(1)}h</strong></div><div><span>絞り込み後</span><i><b style={{width:`${rate}%`}}/></i><strong>{toBeH.toFixed(1)}h</strong></div></div><dl><div><dt>削減人日</dt><dd>{(hoursDay?saved/hoursDay:0).toFixed(1)} 人日</dd></div><div><dt>現状費用</dt><dd>¥{Math.round(asCost).toLocaleString()}</dd></div><div><dt>導入後費用</dt><dd>¥{Math.round(toCost).toLocaleString()}</dd></div><div className={diff<0?'negative':''}><dt>{diff>=0?'差額':'この仮定では費用増'}</dt><dd>{diff>=0?'-':'+'}¥{Math.abs(Math.round(diff)).toLocaleString()}</dd></div></dl></div></div><div className="formula-card"><h2>計算式</h2><code>現状費用 = {total}筆 × {minutes}分 ÷ 60 × {people}人 × ¥{wage.toLocaleString()}/人時</code><code>導入後費用 = ¥{ops.toLocaleString()} + {rate}% × {total}筆 × {minutes}分 ÷ 60 × {people}人 × ¥{wage.toLocaleString()}/人時</code></div></section>
}

function Method({manifest,methodology}:{manifest:Manifest;methodology:Methodology}){
  const actual=isActual(manifest)
  return <section className="standard-page method-page"><div className="page-title-row"><div><h1>この判定について</h1></div></div>
    <div className="method-grid"><article><div className="article-icon"><SatelliteIcon/></div><h2>1. 2つの衛星で観測</h2><p>Sentinel-1のVHで水面と整合する後方散乱の低下を、Sentinel-2のNDVIで植生の立ち上がりとピークを見ます。</p></article><article><div className="article-icon"><Filter/></div><h2>2. 4イベントを検出</h2><p>湛水、生育開始、生育ピーク、収穫後低下を独立に判定。丸め前の値を使い、観測不足は無理に補完しません。</p></article><article><div className="article-icon"><ShieldCheck/></div><h2>3. 人が最終確認</h2><p>衛星判定は現地確認先の優先順位づけに限定します。休耕や作物を確定する行政判断には使いません。</p></article></div>
    <section className="method-section"><h2>固定した判定基準</h2><div className="threshold-grid"><div><span>SAR 湛水低下</span><strong>≥ {manifest.thresholds.sarFloodDropDb} dB</strong><small>3–4月 → 5–6月</small></div><div><span>NDVI 生育上昇</span><strong>≥ {manifest.thresholds.ndviGrowthRise.toFixed(2)}</strong><small>5月 → 6–9月ピーク</small></div><div><span>NDVI ピーク</span><strong>≥ {manifest.thresholds.ndviPeak.toFixed(2)}</strong><small>6–9月の月中央値最大</small></div><div><span>NDVI 収穫低下</span><strong>≥ {manifest.thresholds.ndviHarvestDrop.toFixed(2)}</strong><small>ピーク → 9–11月</small></div></div></section>
    <section className="method-section"><h2>状態への変換</h2><div className="rule-table"><div className="rule-head"><span>湛水</span><span>NDVI生育</span><span>主判定</span><span>補助判定</span></div>{[['あり','あり','cultivation_signal','paddy_signal'],['なし','あり','cultivation_signal','upland_crop_signal'],['なし','なし','fallow_candidate','mixed_or_unknown'],['あり','なし','review_required','mixed_or_unknown'],['不明','あり','cultivation_signal','not_evaluated'],['任意','不明','insufficient_observation','not_evaluated']].map((r,i)=><div key={i}><span>{r[0]}</span><span>{r[1]}</span><span className={`status-pill ${STATUS[r[2] as Status].tone}`}>{STATUS[r[2] as Status].label}</span><span>{SUBTYPE[r[3] as keyof typeof SUBTYPE]}</span></div>)}</div></section>
    <section className="method-section"><h2>感度分析</h2><div className="table-wrap"><table><thead><tr><th>変更項目</th><th>値</th><th>入替筆数</th><th>作付兆候</th><th>休耕可能性</th><th>要確認</th><th>観測不足</th></tr></thead><tbody>{methodology.sensitivity.map((s,i)=><tr key={i}><td>{SENSITIVITY_LABELS[s.parameter]??s.parameter}</td><td>{s.value??'固定基準'}</td><td>{s.changed_fields}</td><td>{s.status_counts.cultivation_signal??0}</td><td>{s.status_counts.fallow_candidate??0}</td><td>{s.status_counts.review_required??0}</td><td>{s.status_counts.insufficient_observation??0}</td></tr>)}</tbody></table></div></section>
    <section className="method-section two-col"><div><h2>データと出典</h2><ul className="source-list"><li><strong>Sentinel-1 RTC / Sentinel-2 L2A</strong><span>{actual?`${manifest.observationSource}から取得した実観測（S1 ${manifest.provenance?.sentinel1?.sceneCount??'—'}シーン／S2 ${manifest.provenance?.sentinel2?.sceneCount??'—'}シーン）`:'衛星観測データ'}</span><a href="https://sentinels.copernicus.eu/documents/247904/690755/Sentinel_Data_Legal_Notice" target="_blank" rel="noreferrer">利用条件</a></li><li><strong>筆ポリゴン 2026年</strong><span>農林水産省、南相馬市データをROI切り出し</span><a href="https://www.maff.go.jp/j/tokei/porigon/" target="_blank" rel="noreferrer">公開ページ</a></li><li><strong>OpenStreetMap</strong><span>対話地図の背景のみ</span><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">著作権とライセンス</a></li><li><strong>処理基盤</strong><span>{manifest.observationSource??'Google Earth Engine'}。クライアントからは接続しません</span></li></ul></div><div><h2>主な限界</h2><ul className="limit-list"><li>雲、観測間隔、混合画素でイベントを見逃すことがあります。</li>{manifest.cloudMask?.differenceFromBaseline&&<li>{manifest.cloudMask.differenceFromBaseline}。今回はSCLと20mバッファで除外しています。</li>}<li>水面のSAR低下は、水田以外の冠水でも起こります。</li><li>2026年境界を2024・2025年へ適用しており、境界時点差があります。</li><li>0.05 ha未満は10m画素との相性が悪く、自動的に要確認です。</li><li>作付兆候は作物名、補助対象、適法性を確定しません。</li></ul></div></section>
  </section>
}
function SatelliteIcon(){return <MapIcon/>}
